import React, { useState } from 'react';
import { ShieldAlert, PhoneCall, Gift, RefreshCw, AlertCircle, X, ChevronRight } from 'lucide-react';

const INTERVENTION_ACTIONS = [
  {
    id: 'waive-load',
    label: 'Waive Exit Load',
    icon: <Gift size={24} style={{ color: 'var(--primary-blue)' }} />,
    template: `Dear {name},

We value your long-term association with FinTrend Analytic Platform. As a token of our appreciation, we are pleased to offer you a special waiver on exit load for redemptions made in the next 30 days.

Please contact your advisor for more details.

Best regards,
FinTrend Analytic Platform Team`
  },
  {
    id: 'schedule-call',
    label: 'Schedule Review Call',
    icon: <PhoneCall size={24} style={{ color: 'var(--success-green)' }} />,
    template: `Dear {name},

Your portfolio needs attention. We would like to schedule a complimentary portfolio review call with our senior advisor to discuss your investment goals and current performance.

Please reply to book a 30-minute session at your convenience.

Best regards,
FinTrend Analytic Platform`
  },
  {
    id: 'offer-switch',
    label: 'Offer Fund Switch',
    icon: <RefreshCw size={24} style={{ color: '#8B5CF6' }} />,
    template: `Dear {name},

We have identified a fund that better aligns with your current investment objectives — the Nifty 50 Index Fund (Expense Ratio: 0.15%), which has been consistently outperforming benchmarks.

Switch today at zero transaction cost.

Best regards,
FinTrend Analytic Platform`
  },
  {
    id: 'flag-advisor',
    label: 'Flag to Senior Advisor',
    icon: <ShieldAlert size={24} style={{ color: 'var(--error-red)' }} />,
    template: `INTERNAL ALERT — HIGH CHURN RISK

Investor: {name}
Risk Level: HIGH (>70% probability)
Trigger: Extended inactivity + elevated redemption pattern

Action Required: Immediate outreach within 24-48 hours. Offer retention package.

Generated by: FinTrend Analytic Platform Churn AI Engine`
  }
];

export default function ChurnPrediction() {
  const [clients, setClients] = useState([
    { name: 'Rakesh Choudhury', age: 31, profile: 'Aggressive', aum: '₹0.80 Cr', risk: 95, inactive: 135, status: 'Pending' },
    { name: 'Gaurav Grover', age: 33, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 438, status: 'Pending' },
    { name: 'Deepika Dubey', age: 24, profile: 'Aggressive', aum: '₹0.01 Cr', risk: 95, inactive: 688, status: 'Pending' },
    { name: 'Neha Mehta', age: 34, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 201, status: 'Pending' },
    { name: 'Amitabh Gandhi', age: 18, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 252, status: 'Pending' },
    { name: 'Asha Nair', age: 20, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 481, status: 'Pending' },
    { name: 'Nikhil Mehta', age: 27, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 328, status: 'Pending' },
    { name: 'Amit Ganguly', age: 20, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 102, status: 'Pending' },
    { name: 'Rohan Joshi', age: 25, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 102, status: 'Pending' },
    { name: 'Manish Chatterjee', age: 26, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 240, status: 'Pending' },
    { name: 'Vivek Kapoor', age: 35, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 142, status: 'Pending' },
    { name: 'Deepak Singh', age: 28, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 98, status: 'Pending' },
    { name: 'Rahul Dubey', age: 30, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 226, status: 'Pending' },
    { name: 'Vikram Roy', age: 32, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 115, status: 'Pending' },
    { name: 'Kavita Menon', age: 29, profile: 'Aggressive', aum: '₹0.00 Cr', risk: 95, inactive: 110, status: 'Pending' }
  ]);

  // Modal / Wizard States
  const [modalOpen, setModalOpen] = useState(false);
  const [activeClient, setActiveClient] = useState(null);
  const [wizardStep, setWizardStep] = useState(1);
  const [selectedAction, setSelectedAction] = useState(null);
  const [editMessage, setEditMessage] = useState('');
  const [toastMessage, setToastMessage] = useState('');

  const handleRecalculate = () => {
    setToastMessage('Recalculating churn probability matrices...');
    setTimeout(() => {
      setToastMessage('');
    }, 3000);
  };

  const launchWizard = (client) => {
    setActiveClient(client);
    setWizardStep(1);
    setSelectedAction(null);
    setEditMessage('');
    setModalOpen(true);
  };

  const selectAction = (action) => {
    setSelectedAction(action);
    setEditMessage(action.template.replace('{name}', activeClient.name));
    setWizardStep(2);
  };

  const confirmDispatch = () => {
    setClients(prev => prev.map(c => {
      if (c.name === activeClient.name) {
        return { ...c, status: `Active: ${selectedAction.label}` };
      }
      return c;
    }));
    setModalOpen(false);
  };

  return (
    <div>
      {/* Page Header */}
      <div className="page-header-strip">
        <div className="page-title-area">
          <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.72rem', color: 'var(--text-secondary)', marginBottom: '4px' }}>
            <span>FinTrend Analytic Platform</span>
            <ChevronRight size={10} />
            <span style={{ fontWeight: '600', color: 'var(--primary-blue)' }}>Churn Predictor</span>
          </div>
          <h1 className="page-title">Churn Predictor</h1>
          <p className="page-subtitle">AI-powered predictive modeling for investor retention and capital protection</p>
        </div>
      </div>

      {/* CHURN RISK ASSESSMENT KPIs */}
      <div className="card" style={{ marginBottom: '24px' }}>
        <div className="card-title-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
          <div>
            <span style={{ fontSize: '0.68rem', fontWeight: '700', color: 'var(--text-secondary)', letterSpacing: '0.05em' }}>CHURN RISK ASSESSMENT</span>
          </div>
          <button 
            onClick={handleRecalculate}
            className="dropdown-filter-btn"
            style={{ display: 'flex', alignItems: 'center', gap: '4px', padding: '6px 12px', fontSize: '0.72rem' }}
          >
            🔄 Recalculate
          </button>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px' }}>
          {/* Card 1: OVERALL AMC CHURN RISK */}
          <div className="card kpi-card" style={{ minHeight: 'auto', padding: '16px', backgroundColor: 'var(--bg-main)', boxShadow: 'none', border: '1px solid var(--border-color)', margin: 0 }}>
            <span style={{ fontSize: '0.68rem', fontWeight: '700', color: 'var(--text-secondary)' }}>OVERALL AMC CHURN RISK</span>
            <span style={{ fontSize: '1.8rem', fontWeight: '800', margin: '4px 0' }}>45.48%</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.7rem', color: 'var(--text-secondary)' }}>
              <span className="status-badge" style={{ backgroundColor: 'var(--border-color)', color: 'var(--text-secondary)', padding: '1px 6px', fontSize: '0.65rem' }}>- Stable</span>
              <span>avg probability of capital exit</span>
            </div>
          </div>

          {/* Card 2: HIGH RISK THREATS (>= 70%) */}
          <div className="card kpi-card" style={{ minHeight: 'auto', padding: '16px', backgroundColor: 'var(--bg-main)', boxShadow: 'none', border: '1px solid var(--border-color)', margin: 0 }}>
            <span style={{ fontSize: '0.68rem', fontWeight: '700', color: 'var(--text-secondary)' }}>HIGH RISK THREATS (≥70%)</span>
            <span style={{ fontSize: '1.8rem', fontWeight: '800', margin: '4px 0' }}>94</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.7rem', color: 'var(--text-secondary)' }}>
              <span className="status-badge" style={{ backgroundColor: 'var(--error-bg)', color: 'var(--error-red)', padding: '1px 6px', fontSize: '0.65rem' }}>Immediate Action</span>
              <span>investors requiring int...</span>
            </div>
          </div>

          {/* Card 3: POTENTIAL EXIT VOLUME */}
          <div className="card kpi-card" style={{ minHeight: 'auto', padding: '16px', backgroundColor: 'var(--bg-main)', boxShadow: 'none', border: '1px solid var(--border-color)', margin: 0 }}>
            <span style={{ fontSize: '0.68rem', fontWeight: '700', color: 'var(--text-secondary)' }}>POTENTIAL EXIT VOLUME</span>
            <span style={{ fontSize: '1.8rem', fontWeight: '800', margin: '4px 0' }}>₹0.46 Cr</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.7rem', color: 'var(--text-secondary)' }}>
              <span className="status-badge" style={{ backgroundColor: 'var(--error-bg)', color: 'var(--error-red)', padding: '1px 6px', fontSize: '0.65rem' }}>↘ AUM At Risk</span>
              <span>under high churn threat</span>
            </div>
          </div>

          {/* Card 4: AVG CLIENT TENURE */}
          <div className="card kpi-card" style={{ minHeight: 'auto', padding: '16px', backgroundColor: 'var(--bg-main)', boxShadow: 'none', border: '1px solid var(--border-color)', margin: 0 }}>
            <span style={{ fontSize: '0.68rem', fontWeight: '700', color: 'var(--text-secondary)' }}>AVG CLIENT TENURE</span>
            <span style={{ fontSize: '1.8rem', fontWeight: '800', margin: '4px 0' }}>3.4 Years</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.7rem', color: 'var(--text-secondary)' }}>
              <span className="status-badge" style={{ backgroundColor: 'var(--success-bg)', color: 'var(--success-green)', padding: '1px 6px', fontSize: '0.65rem' }}>Sticky Portfolio</span>
              <span>avg active SIP/Lumpsu...</span>
            </div>
          </div>
        </div>
      </div>

      {/* Churn by Age Group progress bars */}
      <div className="card" style={{ marginBottom: '24px' }}>
        <h3 className="card-title" style={{ marginBottom: '4px' }}>Churn by Age Group</h3>
        <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '20px' }}>
          Client age correlation to churn propensity
        </div>

        <div className="portfolio-progress-container" style={{ display: 'flex', flexDirection: 'column', gap: '16px', marginBottom: '24px' }}>
          {/* Age 18-25 Yrs */}
          <div className="progress-row">
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', fontWeight: '600', marginBottom: '4px' }}>
              <span>Age 18-25 Yrs</span>
              <strong style={{ color: 'var(--text-primary)' }}>18.2%</strong>
            </div>
            <div className="progress-track" style={{ height: '8px' }}>
              <div className="progress-fill" style={{ width: '18.2%', backgroundColor: '#10B981' }}></div>
            </div>
          </div>

          {/* Age 26-35 Yrs */}
          <div className="progress-row">
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', fontWeight: '600', marginBottom: '4px' }}>
              <span>Age 26-35 Yrs</span>
              <strong style={{ color: 'var(--text-primary)' }}>26.5%</strong>
            </div>
            <div className="progress-track" style={{ height: '8px' }}>
              <div className="progress-fill" style={{ width: '26.5%', backgroundColor: '#F59E0B' }}></div>
            </div>
          </div>

          {/* Age 36-45 Yrs */}
          <div className="progress-row">
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', fontWeight: '600', marginBottom: '4px' }}>
              <span>Age 36-45 Yrs</span>
              <strong style={{ color: 'var(--text-primary)' }}>41.9%</strong>
            </div>
            <div className="progress-track" style={{ height: '8px' }}>
              <div className="progress-fill" style={{ width: '41.9%', backgroundColor: '#EF4444' }}></div>
            </div>
          </div>

          {/* Age 46-60 Yrs */}
          <div className="progress-row">
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', fontWeight: '600', marginBottom: '4px' }}>
              <span>Age 46-60 Yrs</span>
              <strong style={{ color: 'var(--text-primary)' }}>39.8%</strong>
            </div>
            <div className="progress-track" style={{ height: '8px' }}>
              <div className="progress-fill" style={{ width: '39.8%', backgroundColor: '#F59E0B' }}></div>
            </div>
          </div>

          {/* Age 60+ Yrs */}
          <div className="progress-row">
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', fontWeight: '600', marginBottom: '4px' }}>
              <span>Age 60+ Yrs</span>
              <strong style={{ color: 'var(--text-primary)' }}>40.3%</strong>
            </div>
            <div className="progress-track" style={{ height: '8px' }}>
              <div className="progress-fill" style={{ width: '40.3%', backgroundColor: '#EF4444' }}></div>
            </div>
          </div>
        </div>

        {/* Age-based Insight text */}
        <div style={{ borderTop: '1px solid var(--border-color)', paddingTop: '16px' }}>
          <span style={{ fontSize: '0.68rem', fontWeight: '700', color: 'var(--text-secondary)', letterSpacing: '0.05em' }}>
            AGE-BASED INSIGHT
          </span>
          <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: '4px', lineHeight: '1.5' }}>
            Investors aged 26-35 show higher churn due to market volatility sensitivity. Offer SIP step-up plans and low-cost index funds to retain younger cohorts.
          </p>
        </div>
      </div>

      {/* Main client list */}
      <div className="card" style={{ marginBottom: '24px' }}>
        <div className="card-title-row" style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '4px', marginBottom: '16px' }}>
          <h3 className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <AlertCircle size={18} style={{ color: 'var(--error-red)' }} />
            Flagged Churn Threats (≥70% Probability)
          </h3>
          <span style={{ fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
            15 investors showing critical exit pattern triggers — click row to launch Intervention Wizard
          </span>
        </div>

        <div className="table-responsive">
          <table className="data-table">
            <thead>
              <tr>
                <th>Investor</th>
                <th className="text-right">Age</th>
                <th>Profile</th>
                <th className="text-right">AUM (Cr)</th>
                <th className="text-right">Risk %</th>
                <th className="text-right">Days of Inactivation</th>
                <th className="text-right">Intervene</th>
              </tr>
            </thead>
            <tbody>
              {clients.map((c, index) => {
                const isPending = c.status === 'Pending';
                return (
                  <tr key={index} style={{ cursor: 'pointer' }} onClick={() => launchWizard(c)}>
                    <td style={{ fontWeight: '700', color: 'var(--text-primary)' }}>{c.name}</td>
                    <td className="text-right mono">{c.age}</td>
                    <td style={{ fontWeight: '500', color: 'var(--text-secondary)' }}>{c.profile}</td>
                    <td className="text-right mono" style={{ fontWeight: '600' }}>{c.aum}</td>
                    <td className="text-right mono">
                      <span className="status-badge" style={{ backgroundColor: 'var(--error-bg)', color: 'var(--error-red)', fontWeight: '700', padding: '2px 8px' }}>
                        {c.risk}%
                      </span>
                    </td>
                    <td className="text-right mono" style={{ color: c.inactive > 300 ? 'var(--error-red)' : 'var(--text-secondary)' }}>
                      {c.inactive} Days
                    </td>
                    <td className="text-right" onClick={(e) => e.stopPropagation()}>
                      {isPending ? (
                        <button
                          className="button-primary"
                          onClick={() => launchWizard(c)}
                          style={{ padding: '6px 12px', fontSize: '0.72rem' }}
                        >
                          Launch Wizard
                        </button>
                      ) : (
                        <span className="status-badge" style={{ backgroundColor: 'var(--success-bg)', color: 'var(--success-green)', fontWeight: '600' }}>
                          {c.status}
                        </span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Retention Intervention Wizard Modal */}
      {modalOpen && (
        <div className="modal-overlay" onClick={() => setModalOpen(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <div>
                <h3 className="card-title">Retention Intervention Wizard</h3>
                <div className="modal-title-desc">
                  {wizardStep === 1 ? 'Step 1: Choose Action' : 'Step 2: Review & Edit Message'}
                </div>
              </div>
              <button onClick={() => setModalOpen(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-secondary)' }}>
                <X size={18} />
              </button>
            </div>

            <div className="modal-body">
              <div className="modal-client-meta">
                <span>Client: <strong>{activeClient.name}</strong></span>
                <span>Risk: <strong style={{ color: 'var(--error-red)' }}>{activeClient.risk}% Churn Risk</strong></span>
                <span>Inactivity: <strong>{activeClient.inactive} Days</strong></span>
                <span>AUM: <strong>{activeClient.aum}</strong></span>
              </div>

              {wizardStep === 1 && (
                <div>
                  <p style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', marginTop: '16px' }}>
                    Select the next best action to retain this client.
                  </p>
                  <div className="action-cards-grid">
                    {INTERVENTION_ACTIONS.map(act => (
                      <div key={act.id} className="action-card" onClick={() => selectAction(act)}>
                        <div className="action-card-icon">{act.icon}</div>
                        <div className="action-card-label">{act.label}</div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {wizardStep === 2 && (
                <div>
                  <div style={{ marginTop: '16px', fontSize: '0.78rem', fontWeight: '700', color: 'var(--text-primary)' }}>
                    {selectedAction.label} — Message Preview
                  </div>
                  <textarea
                    value={editMessage}
                    onChange={(e) => setEditMessage(e.target.value)}
                    className="message-textarea"
                  />
                </div>
              )}
            </div>

            <div className="modal-footer">
              <button
                className="dropdown-filter-btn"
                onClick={() => {
                  if (wizardStep === 2) {
                    setWizardStep(1);
                  } else {
                    setModalOpen(false);
                  }
                }}
                style={{ padding: '8px 16px' }}
              >
                {wizardStep === 2 ? '← Back' : 'Cancel'}
              </button>
              {wizardStep === 2 && (
                <button
                  className="button-primary"
                  onClick={confirmDispatch}
                  style={{ padding: '8px 16px' }}
                >
                  Confirm &amp; Dispatch →
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      {toastMessage && (
        <div style={{
          position: 'fixed',
          bottom: '24px',
          right: '24px',
          backgroundColor: '#1E293B',
          color: '#F8FAFC',
          padding: '12px 20px',
          borderRadius: '8px',
          boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.15), 0 4px 6px -4px rgba(0, 0, 0, 0.15)',
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          fontSize: '0.78rem',
          fontWeight: '500',
          zIndex: 1000,
          border: '1px solid #334155',
          animation: 'slideIn 0.2s ease-out'
        }}>
          <span style={{ animation: 'spin 1.5s linear infinite', display: 'inline-block' }}>🔄</span>
          <span>{toastMessage}</span>
        </div>
      )}
    </div>
  );
}
